// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using angularbackend.Data;

#nullable disable

namespace angularbackend.Migrations
{
    [DbContext(typeof(ngDBContext))]
    partial class ngDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("angularbackend.Models.Employees", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AngularEmployee", (string)null);

                    b.HasData(
                        new
                        {
                            id = "288270b6-9b1b-4481-88ef-de68be2f5c6b",
                            department = "IT",
                            email = "d.sha@acc.com",
                            firstName = "Deepak",
                            lastName = "Shakya"
                        },
                        new
                        {
                            id = "7795a5d4-21a7-456a-a01a-638f98bf9f82",
                            department = "BDE",
                            email = "shanal.tripathu@acc.com",
                            firstName = "Shanal",
                            lastName = "Tripathi"
                        },
                        new
                        {
                            id = "5191f053-b17b-426a-8a37-5451128b4362",
                            department = "Writer",
                            email = "richa.dubey@acc.com",
                            firstName = "Richa",
                            lastName = "Dubey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
